// This file is auto-generated by @hey-api/openapi-ts

export const ArchiveEntrySchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        entry_path: {
            type: 'string',
            title: 'Entry Path'
        },
        file_type: {
            type: 'string',
            enum: ['image', 'video', 'audio', 'unknown'],
            title: 'File Type'
        },
        index: {
            type: 'integer',
            title: 'Index'
        }
    },
    type: 'object',
    required: ['name', 'entry_path', 'file_type', 'index'],
    title: 'ArchiveEntry'
} as const;

export const ArchiveListResponseSchema = {
    properties: {
        entries: {
            items: {
                '$ref': '#/components/schemas/ArchiveEntry'
            },
            type: 'array',
            title: 'Entries'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['entries', 'total'],
    title: 'ArchiveListResponse'
} as const;

export const AuthorListItemSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        thumbnail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thumbnail'
        },
        file_count: {
            type: 'integer',
            title: 'File Count'
        }
    },
    type: 'object',
    required: ['name', 'file_count'],
    title: 'AuthorListItem'
} as const;

export const AuthorsResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/AuthorListItem'
            },
            type: 'array',
            title: 'Items'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['items', 'page', 'page_size', 'total'],
    title: 'AuthorsResponse'
} as const;

export const BackfillRequestSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        recursive: {
            type: 'boolean',
            title: 'Recursive',
            default: true
        },
        fill_thumbnail: {
            type: 'boolean',
            title: 'Fill Thumbnail',
            default: true
        },
        fill_meta: {
            type: 'boolean',
            title: 'Fill Meta',
            default: true
        }
    },
    type: 'object',
    required: ['path'],
    title: 'BackfillRequest'
} as const;

export const BackfillResponseSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'ok',
            title: 'Status'
        },
        scanned_files: {
            type: 'integer',
            title: 'Scanned Files'
        },
        backfilled_thumbnails: {
            type: 'integer',
            title: 'Backfilled Thumbnails'
        },
        backfilled_meta: {
            type: 'integer',
            title: 'Backfilled Meta'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['status', 'scanned_files', 'backfilled_thumbnails', 'backfilled_meta', 'message'],
    title: 'BackfillResponse'
} as const;

export const BatchParseItemSchema = {
    properties: {
        filepath: {
            type: 'string',
            title: 'Filepath'
        },
        result: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ParseResponse'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['filepath'],
    title: 'BatchParseItem'
} as const;

export const BatchParseRequestSchema = {
    properties: {
        filepaths: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Filepaths'
        }
    },
    type: 'object',
    required: ['filepaths'],
    title: 'BatchParseRequest'
} as const;

export const BatchParseResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/BatchParseItem'
            },
            type: 'array',
            title: 'Items'
        },
        parsed_count: {
            type: 'integer',
            title: 'Parsed Count'
        },
        total_count: {
            type: 'integer',
            title: 'Total Count'
        }
    },
    type: 'object',
    required: ['items', 'parsed_count', 'total_count'],
    title: 'BatchParseResponse'
} as const;

export const ClearCacheResponseSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'ok',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        deleted_files: {
            type: 'integer',
            title: 'Deleted Files'
        },
        freed_bytes: {
            type: 'integer',
            title: 'Freed Bytes'
        },
        freed_size_readable: {
            type: 'string',
            title: 'Freed Size Readable'
        }
    },
    type: 'object',
    required: ['status', 'message', 'deleted_files', 'freed_bytes', 'freed_size_readable'],
    title: 'ClearCacheResponse'
} as const;

export const CompressImagesRequestSchema = {
    properties: {
        archive_path: {
            type: 'string',
            title: 'Archive Path'
        },
        output_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Output Path'
        },
        max_width: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Width'
        },
        max_height: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Height'
        },
        quality: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quality'
        },
        min_size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Size'
        }
    },
    type: 'object',
    required: ['archive_path'],
    title: 'CompressImagesRequest'
} as const;

export const CompressImagesResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        original_path: {
            type: 'string',
            title: 'Original Path'
        },
        output_path: {
            type: 'string',
            title: 'Output Path'
        },
        original_size: {
            type: 'integer',
            title: 'Original Size'
        },
        compressed_size: {
            type: 'integer',
            title: 'Compressed Size'
        },
        compression_ratio: {
            type: 'number',
            title: 'Compression Ratio'
        },
        processed_images: {
            type: 'integer',
            title: 'Processed Images'
        },
        skipped_images: {
            type: 'integer',
            title: 'Skipped Images'
        },
        validation_passed: {
            type: 'boolean',
            title: 'Validation Passed'
        },
        error_message: {
            type: 'string',
            title: 'Error Message',
            default: ''
        }
    },
    type: 'object',
    required: ['success', 'original_path', 'output_path', 'original_size', 'compressed_size', 'compression_ratio', 'processed_images', 'skipped_images', 'validation_passed'],
    title: 'CompressImagesResponse'
} as const;

export const CoserListItemSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        thumbnail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thumbnail'
        },
        file_count: {
            type: 'integer',
            title: 'File Count'
        }
    },
    type: 'object',
    required: ['name', 'file_count'],
    title: 'CoserListItem'
} as const;

export const CosersResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/CoserListItem'
            },
            type: 'array',
            title: 'Items'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['items', 'page', 'page_size', 'total'],
    title: 'CosersResponse'
} as const;

export const DeletePathRequestSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        }
    },
    type: 'object',
    required: ['path'],
    title: 'DeletePathRequest'
} as const;

export const ExtractStatusSchema = {
    properties: {
        status: {
            type: 'string',
            enum: ['extracting', 'completed', 'error'],
            title: 'Status'
        },
        extracted_count: {
            type: 'integer',
            title: 'Extracted Count'
        },
        total_count: {
            type: 'integer',
            title: 'Total Count'
        },
        cache_dir: {
            type: 'string',
            title: 'Cache Dir'
        }
    },
    type: 'object',
    required: ['status', 'extracted_count', 'total_count', 'cache_dir'],
    title: 'ExtractStatus'
} as const;

export const FileSystemItemSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        item_type: {
            type: 'string',
            enum: ['folder', 'file'],
            title: 'Item Type'
        },
        file_type: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['image', 'video', 'archive', 'audio', 'unknown']
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Type'
        },
        filesize: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filesize'
        },
        mtime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mtime'
        },
        thumbnail_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thumbnail Url'
        },
        recommendation_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommendation Score'
        },
        scan_state: {
            type: 'integer',
            title: 'Scan State',
            default: 0
        },
        watch_state: {
            type: 'integer',
            title: 'Watch State',
            default: 0
        },
        confidence_level: {
            type: 'string',
            enum: ['certain', 'likely_present', 'uncertain'],
            title: 'Confidence Level',
            default: 'uncertain'
        },
        confidence_score: {
            type: 'number',
            title: 'Confidence Score',
            default: 0.2
        },
        image_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Count'
        },
        video_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Count'
        },
        audio_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Audio Count'
        },
        avg_image_size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Image Size'
        }
    },
    type: 'object',
    required: ['name', 'path', 'item_type'],
    title: 'FileSystemItem'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HistoryItemSchema = {
    properties: {
        filepath: {
            type: 'string',
            title: 'Filepath'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        file_type: {
            type: 'string',
            enum: ['image', 'video', 'archive', 'audio', 'unknown'],
            title: 'File Type'
        },
        filesize: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filesize'
        },
        mtime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mtime'
        },
        thumbnail_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thumbnail Url'
        },
        read_at: {
            type: 'integer',
            title: 'Read At'
        },
        page_current: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Current'
        },
        page_total: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Total'
        },
        file_exists: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Exists'
        }
    },
    type: 'object',
    required: ['filepath', 'filename', 'file_type', 'read_at'],
    title: 'HistoryItem'
} as const;

export const HistoryListResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/HistoryItem'
            },
            type: 'array',
            title: 'Items'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: ['items', 'page', 'page_size', 'total', 'total_pages'],
    title: 'HistoryListResponse'
} as const;

export const HistoryRecordRequestSchema = {
    properties: {
        filepath: {
            type: 'string',
            title: 'Filepath'
        },
        page_current: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Current'
        },
        page_total: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Total'
        },
        position_sec: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Sec'
        },
        duration_sec: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Sec'
        }
    },
    type: 'object',
    required: ['filepath'],
    title: 'HistoryRecordRequest'
} as const;

export const HistoryRecordResponseSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'ok',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'HistoryRecordResponse'
} as const;

export const ListResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/FileSystemItem'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['items'],
    title: 'ListResponse'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MovePathRequestSchema = {
    properties: {
        source_path: {
            type: 'string',
            title: 'Source Path'
        },
        dest_path: {
            type: 'string',
            title: 'Dest Path'
        }
    },
    type: 'object',
    required: ['source_path', 'dest_path'],
    title: 'MovePathRequest'
} as const;

export const ParseResponseSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        authors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Authors'
        },
        cosers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Cosers',
            default: []
        },
        group: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Group'
        },
        raw_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Raw Tags'
        },
        event: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Event'
        },
        date_tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Tag'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        pack_kind: {
            type: 'string',
            title: 'Pack Kind',
            default: 'manga'
        }
    },
    type: 'object',
    required: ['title', 'authors', 'raw_tags', 'type'],
    title: 'ParseResponse'
} as const;

export const PathOperationResponseSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'ok',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        dest_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dest Path'
        }
    },
    type: 'object',
    required: ['status', 'message', 'path'],
    title: 'PathOperationResponse'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RenameRequestSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        new_name: {
            type: 'string',
            title: 'New Name'
        }
    },
    type: 'object',
    required: ['path', 'new_name'],
    title: 'RenameRequest'
} as const;

export const RootItemSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        dirname: {
            type: 'string',
            title: 'Dirname'
        }
    },
    type: 'object',
    required: ['path', 'dirname'],
    title: 'RootItem'
} as const;

export const ScanRequestSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        recursive: {
            type: 'boolean',
            title: 'Recursive',
            default: true
        }
    },
    type: 'object',
    required: ['path'],
    title: 'ScanRequest'
} as const;

export const ScanStartResponseSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'started',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        path: {
            type: 'string',
            title: 'Path'
        }
    },
    type: 'object',
    required: ['status', 'message', 'path'],
    title: 'ScanStartResponse'
} as const;

export const ScanStatusItemSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        status: {
            type: 'string',
            enum: ['running', 'completed', 'error'],
            title: 'Status'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        recursive: {
            type: 'boolean',
            title: 'Recursive',
            default: true
        },
        scanned_folders: {
            type: 'integer',
            title: 'Scanned Folders',
            default: 0
        },
        scanned_files: {
            type: 'integer',
            title: 'Scanned Files',
            default: 0
        },
        parsed_files: {
            type: 'integer',
            title: 'Parsed Files',
            default: 0
        },
        watcher_active: {
            type: 'boolean',
            title: 'Watcher Active',
            default: false
        },
        started_at: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        }
    },
    type: 'object',
    required: ['path', 'status'],
    title: 'ScanStatusItem'
} as const;

export const SearchRequestSchema = {
    properties: {
        q: {
            type: 'string',
            title: 'Q',
            default: ''
        },
        scopes: {
            items: {
                type: 'string',
                enum: ['file', 'author', 'coser', 'tag']
            },
            type: 'array',
            title: 'Scopes'
        },
        mode: {
            type: 'string',
            enum: ['exact', 'hybrid'],
            title: 'Mode',
            default: 'hybrid'
        },
        presence_filter: {
            type: 'string',
            enum: ['all', 'watched', 'scanned_recent'],
            title: 'Presence Filter',
            default: 'all'
        }
    },
    type: 'object',
    title: 'SearchRequest'
} as const;

export const SearchResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/FileSystemItem'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['items', 'total'],
    title: 'SearchResponse'
} as const;

export const SettingsResponseSchema = {
    properties: {
        favorite_dir: {
            type: 'string',
            title: 'Favorite Dir'
        },
        fs_roots: {
            type: 'string',
            title: 'Fs Roots'
        },
        already_read_dir: {
            type: 'string',
            title: 'Already Read Dir'
        }
    },
    type: 'object',
    required: ['favorite_dir', 'fs_roots', 'already_read_dir'],
    title: 'SettingsResponse'
} as const;

export const SettingsUpdateSchema = {
    properties: {
        favorite_dir: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Favorite Dir'
        },
        fs_roots: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fs Roots'
        },
        already_read_dir: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Already Read Dir'
        }
    },
    type: 'object',
    title: 'SettingsUpdate'
} as const;

export const StoredParseResponseSchema = {
    properties: {
        filepath: {
            type: 'string',
            title: 'Filepath'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        authors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Authors',
            default: []
        },
        cosers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Cosers',
            default: []
        },
        group_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Group Name'
        },
        raw_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Raw Tags',
            default: []
        },
        event: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Event'
        },
        date_tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Tag'
        },
        media_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Type'
        }
    },
    type: 'object',
    required: ['filepath'],
    title: 'StoredParseResponse'
} as const;

export const TagListItemSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        thumbnail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thumbnail'
        },
        file_count: {
            type: 'integer',
            title: 'File Count'
        }
    },
    type: 'object',
    required: ['name', 'file_count'],
    title: 'TagListItem'
} as const;

export const TagsResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/TagListItem'
            },
            type: 'array',
            title: 'Items'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['items', 'page', 'page_size', 'total'],
    title: 'TagsResponse'
} as const;

export const UnzipRequestSchema = {
    properties: {
        archive_path: {
            type: 'string',
            title: 'Archive Path'
        },
        output_dir: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Output Dir'
        }
    },
    type: 'object',
    required: ['archive_path'],
    title: 'UnzipRequest'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const ZipFolderRequestSchema = {
    properties: {
        folder_path: {
            type: 'string',
            title: 'Folder Path'
        },
        output_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Output Path'
        }
    },
    type: 'object',
    required: ['folder_path'],
    title: 'ZipFolderRequest'
} as const;