// This file is auto-generated by @hey-api/openapi-ts

export const FileSystemItemSchema = {
    title: 'FileSystemItem',
    type: 'object',
    required: ['name', 'path', 'item_type'],
    properties: {
        name: {
            type: 'string'
        },
        path: {
            type: 'string'
        },
        item_type: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['folder']
                },
                {
                    type: 'string',
                    enum: ['file']
                }
            ]
        },
        file_type: {
            anyOf: [
                {
                    anyOf: [
                        {
                            type: 'string',
                            enum: ['image']
                        },
                        {
                            type: 'string',
                            enum: ['video']
                        },
                        {
                            type: 'string',
                            enum: ['archive']
                        },
                        {
                            type: 'string',
                            enum: ['audio']
                        },
                        {
                            type: 'string',
                            enum: ['unknown']
                        }
                    ]
                },
                {
                    type: 'null'
                }
            ]
        },
        filesize: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        mtime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        thumbnail_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        likeScore: {
            default: 0,
            type: 'number'
        },
        is_missing: {
            default: 0,
            type: 'integer'
        },
        image_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        video_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        audio_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        avg_image_size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        last_read_at: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const ListResponseSchema = {
    title: 'ListResponse',
    type: 'object',
    required: ['items'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/FileSystemItem'
            }
        }
    }
} as const;

export const RootItemSchema = {
    title: 'RootItem',
    type: 'object',
    required: ['path', 'dirname'],
    properties: {
        path: {
            type: 'string'
        },
        dirname: {
            type: 'string'
        }
    }
} as const;

export const PathOperationResponseSchema = {
    title: 'PathOperationResponse',
    type: 'object',
    required: ['status', 'message', 'path'],
    properties: {
        status: {
            type: 'string',
            enum: ['ok']
        },
        message: {
            type: 'string'
        },
        path: {
            type: 'string'
        },
        dest_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const HistoryItemSchema = {
    title: 'HistoryItem',
    type: 'object',
    required: ['filepath', 'opened_at'],
    properties: {
        id: {
            type: 'integer'
        },
        filepath: {
            type: 'string'
        },
        filename: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        file_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        thumbnail_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        opened_at: {
            type: 'integer'
        }
    }
} as const;

export const HistoryListResponseSchema = {
    title: 'HistoryListResponse',
    type: 'object',
    required: ['items', 'page', 'page_size', 'total', 'total_pages'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/HistoryItem'
            }
        },
        page: {
            type: 'integer'
        },
        page_size: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        },
        total_pages: {
            type: 'integer'
        }
    }
} as const;

export const HistoryRecordRequestSchema = {
    title: 'HistoryRecordRequest',
    type: 'object',
    required: ['filepath'],
    properties: {
        filepath: {
            type: 'string'
        }
    }
} as const;

export const HistoryRecordResponseSchema = {
    title: 'HistoryRecordResponse',
    type: 'object',
    required: ['status'],
    properties: {
        status: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['ok']
                },
                {
                    type: 'string',
                    enum: ['skipped']
                }
            ]
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const SearchRequestSchema = {
    title: 'SearchRequest',
    type: 'object',
    properties: {
        q: {
            default: '',
            type: 'string'
        },
        scopes: {
            type: 'array',
            items: {
                anyOf: [
                    {
                        type: 'string',
                        enum: ['file']
                    },
                    {
                        type: 'string',
                        enum: ['author']
                    },
                    {
                        type: 'string',
                        enum: ['coser']
                    },
                    {
                        type: 'string',
                        enum: ['tag']
                    }
                ]
            }
        },
        mode: {
            default: 'fuzzy',
            anyOf: [
                {
                    type: 'string',
                    enum: ['exact']
                },
                {
                    type: 'string',
                    enum: ['fuzzy']
                },
                {
                    type: 'string',
                    enum: ['local-check']
                }
            ]
        },
        presence_filter: {
            default: 'all',
            anyOf: [
                {
                    type: 'string',
                    enum: ['all']
                },
                {
                    type: 'string',
                    enum: ['watched']
                },
                {
                    type: 'string',
                    enum: ['scanned_recent']
                }
            ]
        },
        limit: {
            default: 200,
            type: 'integer'
        },
        offset: {
            default: 0,
            type: 'integer'
        }
    }
} as const;

export const SearchResponseSchema = {
    title: 'SearchResponse',
    type: 'object',
    required: ['items', 'total'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/FileSystemItem'
            }
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const LocalCheckHitSchema = {
    title: 'LocalCheckHit',
    type: 'object',
    required: ['name', 'path', 'thumbnail_url', 'match_level', 'confidence'],
    properties: {
        name: {
            type: 'string'
        },
        path: {
            type: 'string'
        },
        thumbnail_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        match_level: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['downloaded']
                },
                {
                    type: 'string',
                    enum: ['likely']
                },
                {
                    type: 'string',
                    enum: ['same_author']
                },
                {
                    type: 'string',
                    enum: ['different']
                }
            ]
        },
        confidence: {
            type: 'number'
        }
    }
} as const;

export const LocalCheckResultSchema = {
    title: 'LocalCheckResult',
    type: 'object',
    required: ['q', 'match_level', 'confidence', 'reason', 'hits'],
    properties: {
        q: {
            type: 'string'
        },
        match_level: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['downloaded']
                },
                {
                    type: 'string',
                    enum: ['likely']
                },
                {
                    type: 'string',
                    enum: ['same_author']
                },
                {
                    type: 'string',
                    enum: ['different']
                }
            ]
        },
        confidence: {
            type: 'number'
        },
        reason: {
            type: 'string'
        },
        hits: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/LocalCheckHit'
            }
        }
    }
} as const;

export const LocalCheckBatchRequestSchema = {
    title: 'LocalCheckBatchRequest',
    type: 'object',
    properties: {
        queries: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        limit: {
            default: 5,
            type: 'integer'
        },
        presence_filter: {
            default: 'all',
            anyOf: [
                {
                    type: 'string',
                    enum: ['all']
                },
                {
                    type: 'string',
                    enum: ['watched']
                },
                {
                    type: 'string',
                    enum: ['scanned_recent']
                }
            ]
        }
    }
} as const;

export const LocalCheckBatchResponseSchema = {
    title: 'LocalCheckBatchResponse',
    type: 'object',
    required: ['results'],
    properties: {
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/LocalCheckResult'
            }
        }
    }
} as const;

export const SettingsResponseSchema = {
    title: 'SettingsResponse',
    type: 'object',
    required: ['favorite_dir', 'fs_roots', 'already_read_dir', 'move_place_dir', 'env_file_path', 'db_file_path'],
    properties: {
        favorite_dir: {
            type: 'string'
        },
        fs_roots: {
            type: 'string'
        },
        already_read_dir: {
            type: 'string'
        },
        move_place_dir: {
            type: 'string'
        },
        env_file_path: {
            type: 'string'
        },
        db_file_path: {
            type: 'string'
        }
    }
} as const;

export const SettingsUpdateSchema = {
    title: 'SettingsUpdate',
    type: 'object',
    properties: {
        favorite_dir: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        fs_roots: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        already_read_dir: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        move_place_dir: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const ParseResponseSchema = {
    title: 'ParseResponse',
    type: 'object',
    required: ['title', 'authors', 'raw_tags', 'type'],
    properties: {
        title: {
            type: 'string'
        },
        authors: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        cosers: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        group: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        raw_tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        event: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        date_tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        type: {
            type: 'string'
        },
        pack_kind: {
            default: 'manga',
            type: 'string'
        }
    }
} as const;

export const StoredParseResponseSchema = {
    title: 'StoredParseResponse',
    type: 'object',
    required: ['filepath'],
    properties: {
        filepath: {
            type: 'string'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        authors: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        cosers: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        group_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        raw_tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        event: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        date_tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        media_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const BatchParseItemSchema = {
    title: 'BatchParseItem',
    type: 'object',
    required: ['filepath'],
    properties: {
        filepath: {
            type: 'string'
        },
        result: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ParseResponse'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const BatchParseRequestSchema = {
    title: 'BatchParseRequest',
    type: 'object',
    required: ['filepaths'],
    properties: {
        filepaths: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const BatchParseResponseSchema = {
    title: 'BatchParseResponse',
    type: 'object',
    required: ['items', 'parsed_count', 'total_count'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BatchParseItem'
            }
        },
        parsed_count: {
            type: 'integer'
        },
        total_count: {
            type: 'integer'
        }
    }
} as const;

export const ArchiveEntrySchema = {
    title: 'ArchiveEntry',
    type: 'object',
    required: ['name', 'entry_path', 'file_type', 'index'],
    properties: {
        name: {
            type: 'string'
        },
        entry_path: {
            type: 'string'
        },
        file_type: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['image']
                },
                {
                    type: 'string',
                    enum: ['video']
                },
                {
                    type: 'string',
                    enum: ['audio']
                },
                {
                    type: 'string',
                    enum: ['unknown']
                }
            ]
        },
        index: {
            type: 'integer'
        }
    }
} as const;

export const ArchiveListResponseSchema = {
    title: 'ArchiveListResponse',
    type: 'object',
    required: ['entries', 'total'],
    properties: {
        entries: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ArchiveEntry'
            }
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const ExtractStatusSchema = {
    title: 'ExtractStatus',
    type: 'object',
    required: ['status', 'extracted_count', 'total_count', 'cache_dir'],
    properties: {
        status: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['extracting']
                },
                {
                    type: 'string',
                    enum: ['completed']
                },
                {
                    type: 'string',
                    enum: ['error']
                }
            ]
        },
        extracted_count: {
            type: 'integer'
        },
        total_count: {
            type: 'integer'
        },
        cache_dir: {
            type: 'string'
        },
        entries: {
            anyOf: [
                {
                    type: 'array',
                    items: {
                        '$ref': '#/components/schemas/ArchiveEntry'
                    }
                },
                {
                    type: 'null'
                }
            ]
        },
        mtime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        filesize: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const CompressImagesRequestSchema = {
    title: 'CompressImagesRequest',
    type: 'object',
    required: ['archive_path'],
    properties: {
        archive_path: {
            type: 'string'
        },
        output_mode: {
            anyOf: [
                {
                    anyOf: [
                        {
                            type: 'string',
                            enum: ['new']
                        },
                        {
                            type: 'string',
                            enum: ['replace']
                        }
                    ]
                },
                {
                    type: 'null'
                }
            ]
        },
        max_height: {
            anyOf: [
                {
                    default: 1600,
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        quality: {
            anyOf: [
                {
                    default: 85,
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        min_size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const CompressImagesResponseSchema = {
    title: 'CompressImagesResponse',
    type: 'object',
    required: ['success', 'original_path', 'output_path', 'original_size', 'compressed_size', 'compression_ratio', 'processed_images', 'skipped_images', 'validation_passed'],
    properties: {
        success: {
            type: 'boolean'
        },
        original_path: {
            type: 'string'
        },
        output_path: {
            type: 'string'
        },
        original_size: {
            type: 'integer'
        },
        compressed_size: {
            type: 'integer'
        },
        compression_ratio: {
            type: 'number'
        },
        processed_images: {
            type: 'integer'
        },
        skipped_images: {
            type: 'integer'
        },
        validation_passed: {
            type: 'boolean'
        },
        error_message: {
            default: '',
            type: 'string'
        }
    }
} as const;

export const ScanRequestSchema = {
    title: 'ScanRequest',
    type: 'object',
    required: ['path'],
    properties: {
        path: {
            type: 'string'
        },
        recursive: {
            default: true,
            type: 'boolean'
        }
    }
} as const;

export const ScanStartResponseSchema = {
    title: 'ScanStartResponse',
    type: 'object',
    required: ['status', 'message', 'path'],
    properties: {
        status: {
            type: 'string',
            enum: ['started']
        },
        message: {
            type: 'string'
        },
        path: {
            type: 'string'
        }
    }
} as const;

export const ScanStatusItemSchema = {
    title: 'ScanStatusItem',
    type: 'object',
    required: ['path', 'status'],
    properties: {
        path: {
            type: 'string'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['running']
                },
                {
                    type: 'string',
                    enum: ['completed']
                },
                {
                    type: 'string',
                    enum: ['error']
                }
            ]
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        recursive: {
            default: true,
            type: 'boolean'
        },
        scanned_folders: {
            default: 0,
            type: 'integer'
        },
        scanned_files: {
            default: 0,
            type: 'integer'
        },
        parsed_files: {
            default: 0,
            type: 'integer'
        },
        watcher_active: {
            default: false,
            type: 'boolean'
        },
        started_at: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        finished_at: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const BackfillRequestSchema = {
    title: 'BackfillRequest',
    type: 'object',
    required: ['path'],
    properties: {
        path: {
            type: 'string'
        },
        recursive: {
            default: true,
            type: 'boolean'
        },
        fill_thumbnail: {
            default: true,
            type: 'boolean'
        },
        fill_meta: {
            default: true,
            type: 'boolean'
        }
    }
} as const;

export const BackfillResponseSchema = {
    title: 'BackfillResponse',
    type: 'object',
    required: ['status', 'scanned_files', 'backfilled_thumbnails', 'backfilled_meta', 'message'],
    properties: {
        status: {
            type: 'string',
            enum: ['ok']
        },
        scanned_files: {
            type: 'integer'
        },
        backfilled_thumbnails: {
            type: 'integer'
        },
        backfilled_meta: {
            type: 'integer'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const ClearCacheResponseSchema = {
    title: 'ClearCacheResponse',
    type: 'object',
    required: ['status', 'message', 'deleted_files', 'freed_bytes', 'freed_size_readable'],
    properties: {
        status: {
            type: 'string',
            enum: ['ok']
        },
        message: {
            type: 'string'
        },
        deleted_files: {
            type: 'integer'
        },
        freed_bytes: {
            type: 'integer'
        },
        freed_size_readable: {
            type: 'string'
        }
    }
} as const;

export const MovePathRequestSchema = {
    title: 'MovePathRequest',
    type: 'object',
    required: ['source_path', 'dest_path'],
    properties: {
        source_path: {
            type: 'string'
        },
        dest_path: {
            type: 'string'
        }
    }
} as const;

export const DeletePathRequestSchema = {
    title: 'DeletePathRequest',
    type: 'object',
    required: ['path'],
    properties: {
        path: {
            type: 'string'
        },
        permanently: {
            default: false,
            type: 'boolean'
        }
    }
} as const;

export const ZipFolderRequestSchema = {
    title: 'ZipFolderRequest',
    type: 'object',
    required: ['folder_path'],
    properties: {
        folder_path: {
            type: 'string'
        },
        output_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const RenameRequestSchema = {
    title: 'RenameRequest',
    type: 'object',
    required: ['path', 'new_name'],
    properties: {
        path: {
            type: 'string'
        },
        new_name: {
            type: 'string'
        }
    }
} as const;

export const UnzipRequestSchema = {
    title: 'UnzipRequest',
    type: 'object',
    required: ['archive_path'],
    properties: {
        archive_path: {
            type: 'string'
        },
        output_dir: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const MkdirRequestSchema = {
    title: 'MkdirRequest',
    type: 'object',
    required: ['path'],
    properties: {
        path: {
            type: 'string'
        }
    }
} as const;

export const ResolvePathResponseSchema = {
    title: 'ResolvePathResponse',
    type: 'object',
    required: ['path', 'exists', 'is_dir'],
    properties: {
        path: {
            type: 'string'
        },
        exists: {
            type: 'boolean'
        },
        is_dir: {
            type: 'boolean'
        }
    }
} as const;

export const TagListItemSchema = {
    title: 'TagListItem',
    type: 'object',
    required: ['name', 'file_count'],
    properties: {
        name: {
            type: 'string'
        },
        thumbnail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        file_count: {
            type: 'integer'
        },
        recommendation_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const AuthorListItemSchema = {
    title: 'AuthorListItem',
    type: 'object',
    required: ['name', 'file_count'],
    properties: {
        name: {
            type: 'string'
        },
        thumbnail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        file_count: {
            type: 'integer'
        },
        recommendation_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const CoserListItemSchema = {
    title: 'CoserListItem',
    type: 'object',
    required: ['name', 'file_count'],
    properties: {
        name: {
            type: 'string'
        },
        thumbnail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        file_count: {
            type: 'integer'
        },
        recommendation_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const TagsQuerySchema = {
    title: 'TagsQuery',
    type: 'object',
    properties: {
        page: {
            minimum: 1,
            default: 1,
            type: 'integer'
        },
        page_size: {
            minimum: 1,
            maximum: 100,
            default: 24,
            type: 'integer'
        },
        sort_by: {
            default: 'count',
            anyOf: [
                {
                    type: 'string',
                    enum: ['count']
                },
                {
                    type: 'string',
                    enum: ['name']
                }
            ]
        },
        sort_order: {
            default: 'desc',
            anyOf: [
                {
                    type: 'string',
                    enum: ['asc']
                },
                {
                    type: 'string',
                    enum: ['desc']
                }
            ]
        }
    }
} as const;

export const AuthorsQuerySchema = {
    title: 'AuthorsQuery',
    type: 'object',
    properties: {
        page: {
            minimum: 1,
            default: 1,
            type: 'integer'
        },
        page_size: {
            minimum: 1,
            maximum: 100,
            default: 24,
            type: 'integer'
        },
        sort_by: {
            default: 'count',
            anyOf: [
                {
                    type: 'string',
                    enum: ['count']
                },
                {
                    type: 'string',
                    enum: ['name']
                }
            ]
        },
        sort_order: {
            default: 'desc',
            anyOf: [
                {
                    type: 'string',
                    enum: ['asc']
                },
                {
                    type: 'string',
                    enum: ['desc']
                }
            ]
        }
    }
} as const;

export const CosersQuerySchema = {
    title: 'CosersQuery',
    type: 'object',
    properties: {
        page: {
            minimum: 1,
            default: 1,
            type: 'integer'
        },
        page_size: {
            minimum: 1,
            maximum: 100,
            default: 24,
            type: 'integer'
        },
        sort_by: {
            default: 'count',
            anyOf: [
                {
                    type: 'string',
                    enum: ['count']
                },
                {
                    type: 'string',
                    enum: ['name']
                }
            ]
        },
        sort_order: {
            default: 'desc',
            anyOf: [
                {
                    type: 'string',
                    enum: ['asc']
                },
                {
                    type: 'string',
                    enum: ['desc']
                }
            ]
        }
    }
} as const;

export const TagsResponseSchema = {
    title: 'TagsResponse',
    type: 'object',
    required: ['items', 'page', 'page_size', 'total'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/TagListItem'
            }
        },
        page: {
            type: 'integer'
        },
        page_size: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const AuthorsResponseSchema = {
    title: 'AuthorsResponse',
    type: 'object',
    required: ['items', 'page', 'page_size', 'total'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/AuthorListItem'
            }
        },
        page: {
            type: 'integer'
        },
        page_size: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const CosersResponseSchema = {
    title: 'CosersResponse',
    type: 'object',
    required: ['items', 'page', 'page_size', 'total'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CoserListItem'
            }
        },
        page: {
            type: 'integer'
        },
        page_size: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const LibraryOverviewResponseSchema = {
    title: 'LibraryOverviewResponse',
    type: 'object',
    required: ['archives', 'videos', 'images', 'audio', 'folders'],
    properties: {
        archives: {
            type: 'integer'
        },
        videos: {
            type: 'integer'
        },
        images: {
            type: 'integer'
        },
        audio: {
            type: 'integer'
        },
        folders: {
            type: 'integer'
        }
    }
} as const;

export const ActivityItemSchema = {
    title: 'ActivityItem',
    type: 'object',
    required: ['activity_type', 'status', 'created_at'],
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        },
        activity_type: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        task_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        target_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        context: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            type: 'integer'
        }
    }
} as const;

export const RecentActivityResponseSchema = {
    title: 'RecentActivityResponse',
    type: 'object',
    required: ['items'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ActivityItem'
            }
        }
    }
} as const;

export const TopFoldersResponseSchema = {
    title: 'TopFoldersResponse',
    type: 'object',
    required: ['folder_pathes'],
    properties: {
        folder_pathes: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const MkdirResponseSchema = {
    title: 'MkdirResponse',
    type: 'object',
    required: ['status'],
    properties: {
        status: {
            type: 'string',
            enum: ['ok']
        }
    }
} as const;