// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { FilesystemGetRootsResponse, FilesystemListDirectoryData, FilesystemListDirectoryResponse, FilesystemScanDirectoryData, FilesystemScanDirectoryResponse, FilesystemScanAndWatchData, FilesystemScanAndWatchResponse, FilesystemGetScanStatusData, FilesystemGetScanStatusResponse, FilesystemGetThumbnailData, FilesystemGetThumbnailResponse, FilesystemListArchiveData, FilesystemListArchiveResponse, FilesystemExtractArchiveData, FilesystemExtractArchiveResponse, FilesystemGetArchiveFileData, FilesystemGetArchiveFileResponse, FilesystemGetFileData, FilesystemGetFileResponse, SearchSearchFilesData, SearchSearchFilesResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsHealthCheckResponse } from './types.gen';

export class FilesystemService {
    /**
     * Get Roots
     * Get configured root directories.
     * @returns RootItem Successful Response
     * @throws ApiError
     */
    public static getRoots(): CancelablePromise<FilesystemGetRootsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/roots'
        });
    }
    
    /**
     * List Directory
     * List contents of a directory.
     * @param data The data for the request.
     * @param data.path Directory path to list
     * @returns ListResponse Successful Response
     * @throws ApiError
     */
    public static listDirectory(data: FilesystemListDirectoryData): CancelablePromise<FilesystemListDirectoryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/list',
            query: {
                path: data.path
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Scan Directory
     * Scan a directory and optionally recurse into subfolders.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ScanStartResponse Successful Response
     * @throws ApiError
     */
    public static scanDirectory(data: FilesystemScanDirectoryData): CancelablePromise<FilesystemScanDirectoryResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/scan',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Scan And Watch
     * Scan a directory recursively and start watchdog listener.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ScanStartResponse Successful Response
     * @throws ApiError
     */
    public static scanAndWatch(data: FilesystemScanAndWatchData): CancelablePromise<FilesystemScanAndWatchResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/scan-watch',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Get Scan Status
     * Get background scan status for all paths or one path.
     * @param data The data for the request.
     * @param data.path Optional path filter
     * @returns ScanStatusItem Successful Response
     * @throws ApiError
     */
    public static getScanStatus(data: FilesystemGetScanStatusData = {}): CancelablePromise<FilesystemGetScanStatusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/scan-status',
            query: {
                path: data.path
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Thumbnail
     * Get or generate thumbnail for a file.
     * @param data The data for the request.
     * @param data.path File path for thumbnail
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getThumbnail(data: FilesystemGetThumbnailData): CancelablePromise<FilesystemGetThumbnailResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/thumb',
            query: {
                path: data.path
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Archive
     * List contents of an archive file.
     * @param data The data for the request.
     * @param data.path Archive file path
     * @returns ArchiveListResponse Successful Response
     * @throws ApiError
     */
    public static listArchive(data: FilesystemListArchiveData): CancelablePromise<FilesystemListArchiveResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/archive/list',
            query: {
                path: data.path
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Extract Archive
     * Extract archive with prioritized extraction of current page vicinity.
     * @param data The data for the request.
     * @param data.path Archive file path
     * @param data.page Current page number for prioritized extraction
     * @returns ExtractStatus Successful Response
     * @throws ApiError
     */
    public static extractArchive(data: FilesystemExtractArchiveData): CancelablePromise<FilesystemExtractArchiveResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/archive/extract',
            query: {
                path: data.path,
                page: data.page
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Archive File
     * Get a file from extracted archive cache.
     * @param data The data for the request.
     * @param data.path Archive file path
     * @param data.entry Entry path within archive
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getArchiveFile(data: FilesystemGetArchiveFileData): CancelablePromise<FilesystemGetArchiveFileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/archive/file',
            query: {
                path: data.path,
                entry: data.entry
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get File
     * Serve a file directly from disk.
     * @param data The data for the request.
     * @param data.path File path
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getFile(data: FilesystemGetFileData): CancelablePromise<FilesystemGetFileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/file',
            query: {
                path: data.path
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SearchService {
    /**
     * Search Files
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SearchResponse Successful Response
     * @throws ApiError
     */
    public static searchFiles(data: SearchSearchFilesData): CancelablePromise<SearchSearchFilesResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/search',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}