// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ListTagsData, ListTagsResponse, ListAuthorsData, ListAuthorsResponse, ListCosersData, ListCosersResponse, GetRootsResponse, GetDrivesResponse, ListDirectoryData, ListDirectoryResponse, GetLibraryOverviewResponse, GetRecentActivityData, GetRecentActivityResponse, GetTopOpenedFoldersData, GetTopOpenedFoldersResponse, ScanDirectoryData, ScanDirectoryResponse, ScanFavoriteResponse, BackfillData, BackfillResponse2, ScanAndWatchData, ScanAndWatchResponse, GetScanStatusData, GetScanStatusResponse, MoveFileData, MoveFileResponse, MoveFolderData, MoveFolderResponse, DeletePathData, DeletePathResponse, RenameItemData, RenameItemResponse, DownloadFileData, DownloadFileResponse, DownloadFileFullData, DownloadFileFullResponse, ServeFileData, ServeFileResponse, EnsureDirData, EnsureDirResponse, ResolvePathData, ResolvePathResponse2, ZipFolderData, ZipFolderResponse, UnzipData, UnzipResponse, ListArchiveData, ListArchiveResponse, ExtractArchiveData, ExtractArchiveResponse, GetArchiveFileData, GetArchiveFileResponse, ClearExtractCacheResponse, CompressImagesData, CompressImagesResponse2, ListHistoryData, ListHistoryResponse, RecordHistoryData, RecordHistoryResponse, GetParseResultData, GetParseResultResponse, ParseBatchData, ParseBatchResponse, SearchFilesData, SearchFilesResponse, LocalCheckBatchData, LocalCheckBatchResponse2, GetSettingsResponse, UpdateSettingsData, UpdateSettingsResponse, VerifyFilesResponse, GetThumbnailData, GetThumbnailResponse } from './types.gen';

export class EntitiesService {
    /**
     * 获取标签列表（分页，含文件数）
     * @param data The data for the request.
     * @param data.page
     * @param data.pageSize
     * @param data.sortBy
     * @param data.sortOrder
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static listTags(data: ListTagsData = {}): CancelablePromise<ListTagsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/tags',
            query: {
                page: data.page,
                page_size: data.pageSize,
                sort_by: data.sortBy,
                sort_order: data.sortOrder
            }
        });
    }
    
    /**
     * 获取作者列表（分页，含文件数）
     * @param data The data for the request.
     * @param data.page
     * @param data.pageSize
     * @param data.sortBy
     * @param data.sortOrder
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static listAuthors(data: ListAuthorsData = {}): CancelablePromise<ListAuthorsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/authors',
            query: {
                page: data.page,
                page_size: data.pageSize,
                sort_by: data.sortBy,
                sort_order: data.sortOrder
            }
        });
    }
    
    /**
     * 获取 Coser 列表（分页，含文件数）
     * @param data The data for the request.
     * @param data.page
     * @param data.pageSize
     * @param data.sortBy
     * @param data.sortOrder
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static listCosers(data: ListCosersData = {}): CancelablePromise<ListCosersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/cosers',
            query: {
                page: data.page,
                page_size: data.pageSize,
                sort_by: data.sortBy,
                sort_order: data.sortOrder
            }
        });
    }
}

export class FilesystemService {
    /**
     * 获取配置的根目录列表
     * @returns RootItem Default Response
     * @throws ApiError
     */
    public static getRoots(): CancelablePromise<GetRootsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/roots'
        });
    }
    
    /**
     * 获取系统盘符 (Windows)
     * @returns RootItem Default Response
     * @throws ApiError
     */
    public static getDrives(): CancelablePromise<GetDrivesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/drives'
        });
    }
    
    /**
     * 列出目录内容（文件+文件夹）
     * @param data The data for the request.
     * @param data.path
     * @param data.sortBy
     * @param data.sortOrder
     * @param data.hasVideo
     * @param data.hasAudio
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static listDirectory(data: ListDirectoryData): CancelablePromise<ListDirectoryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/listdir',
            query: {
                path: data.path,
                sort_by: data.sortBy,
                sort_order: data.sortOrder,
                has_video: data.hasVideo,
                has_audio: data.hasAudio
            }
        });
    }
    
    /**
     * 获取库概览统计
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static getLibraryOverview(): CancelablePromise<GetLibraryOverviewResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/library-overview'
        });
    }
    
    /**
     * 获取最近活动日志
     * @param data The data for the request.
     * @param data.limit
     * @param data.sinceLatestStartup
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static getRecentActivity(data: GetRecentActivityData = {}): CancelablePromise<GetRecentActivityResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/recent-activity',
            query: {
                limit: data.limit,
                since_latest_startup: data.sinceLatestStartup
            }
        });
    }
    
    /**
     * 获取最常打开的文件夹
     * @param data The data for the request.
     * @param data.limit
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static getTopOpenedFolders(data: GetTopOpenedFoldersData = {}): CancelablePromise<GetTopOpenedFoldersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/top-opened-folders',
            query: {
                limit: data.limit
            }
        });
    }
    
    /**
     * 扫描目录并索引文件
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static scanDirectory(data: ScanDirectoryData): CancelablePromise<ScanDirectoryResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/scan',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 扫描收藏目录
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static scanFavorite(): CancelablePromise<ScanFavoriteResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/scan-favorite'
        });
    }
    
    /**
     * 生成元数据和缩略图
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static backfill(data: BackfillData): CancelablePromise<BackfillResponse2> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/generate',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 扫描并启动目录文件监听
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static scanAndWatch(data: ScanAndWatchData): CancelablePromise<ScanAndWatchResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/scan-and-watch',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 查询扫描任务状态
     * @param data The data for the request.
     * @param data.path
     * @returns ScanStatusItem Default Response
     * @throws ApiError
     */
    public static getScanStatus(data: GetScanStatusData = {}): CancelablePromise<GetScanStatusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/scan-status',
            query: {
                path: data.path
            }
        });
    }
    
    /**
     * 移动文件
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static moveFile(data: MoveFileData): CancelablePromise<MoveFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/move-file',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 移动文件夹
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static moveFolder(data: MoveFolderData): CancelablePromise<MoveFolderResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/move-folder',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 删除文件或文件夹（回收站/永久）
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static deletePath(data: DeletePathData): CancelablePromise<DeletePathResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/fs/delete',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 重命名文件或文件夹
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static renameItem(data: RenameItemData): CancelablePromise<RenameItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/rename',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 下载文件（attachment）
     * @param data The data for the request.
     * @param data.path
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static downloadFile(data: DownloadFileData): CancelablePromise<DownloadFileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/download',
            query: {
                path: data.path
            }
        });
    }
    
    /**
     * 下载完整文件（带 Content-Length）
     * @param data The data for the request.
     * @param data.path
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static downloadFileFull(data: DownloadFileFullData): CancelablePromise<DownloadFileFullResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/download-full',
            query: {
                path: data.path
            }
        });
    }
    
    /**
     * 直接返回文件流（inline）
     * @param data The data for the request.
     * @param data.path
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static serveFile(data: ServeFileData): CancelablePromise<ServeFileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/file',
            query: {
                path: data.path
            }
        });
    }
    
    /**
     * 创建目录（递归）
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static ensureDir(data: EnsureDirData): CancelablePromise<EnsureDirResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/mkdir',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 解析路径并检查是否存在
     * @param data The data for the request.
     * @param data.path
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static resolvePath(data: ResolvePathData): CancelablePromise<ResolvePathResponse2> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/resolve-path',
            query: {
                path: data.path
            }
        });
    }
    
    /**
     * 将文件夹压缩为 zip
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static zipFolder(data: ZipFolderData): CancelablePromise<ZipFolderResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/zip-folder',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 解压压缩包到目录
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static unzip(data: UnzipData): CancelablePromise<UnzipResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/unzip',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 列出压缩包内文件条目
     * @param data The data for the request.
     * @param data.path
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static listArchive(data: ListArchiveData): CancelablePromise<ListArchiveResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/archive/list',
            query: {
                path: data.path
            }
        });
    }
    
    /**
     * 分步解压压缩包（按页）
     * @param data The data for the request.
     * @param data.path
     * @param data.page
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static extractArchive(data: ExtractArchiveData): CancelablePromise<ExtractArchiveResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/archive/extract',
            query: {
                path: data.path,
                page: data.page
            }
        });
    }
    
    /**
     * 获取压缩包内单个文件
     * @param data The data for the request.
     * @param data.path
     * @param data.entry
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static getArchiveFile(data: GetArchiveFileData): CancelablePromise<GetArchiveFileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fs/archive/file',
            query: {
                path: data.path,
                entry: data.entry
            }
        });
    }
    
    /**
     * 清除解压缓存
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static clearExtractCache(): CancelablePromise<ClearExtractCacheResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/fs/clean-extract-cache'
        });
    }
    
    /**
     * 压缩包内图片批量压缩
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static compressImages(data: CompressImagesData): CancelablePromise<CompressImagesResponse2> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fs/archive/compress-images',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class HistoryService {
    /**
     * 获取阅读历史列表（分页）
     * @param data The data for the request.
     * @param data.page
     * @param data.pageSize
     * @param data.sortOrder
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static listHistory(data: ListHistoryData = {}): CancelablePromise<ListHistoryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/history/list',
            query: {
                page: data.page,
                page_size: data.pageSize,
                sort_order: data.sortOrder
            }
        });
    }
    
    /**
     * 记录一次阅读
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static recordHistory(data: RecordHistoryData): CancelablePromise<RecordHistoryResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/history/record',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class ParseService {
    /**
     * 解析单个文件名元数据（作者/标签/标题）
     * @param data The data for the request.
     * @param data.filepath
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static getParseResult(data: GetParseResultData = {}): CancelablePromise<GetParseResultResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/parse',
            query: {
                filepath: data.filepath
            }
        });
    }
    
    /**
     * 批量解析文件名元数据
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static batch(data: ParseBatchData): CancelablePromise<ParseBatchResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/parse/batch',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class SearchService {
    /**
     * 搜索文件（支持文件名/作者/coser/标签）
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static files(data: SearchFilesData): CancelablePromise<SearchFilesResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/search',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 批量本地持有检查（油猴脚本用）
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static localCheckBatch(data: LocalCheckBatchData): CancelablePromise<LocalCheckBatchResponse2> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/search/local-check-batch',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class SettingsService {
    /**
     * 获取当前设置
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static getSettings(): CancelablePromise<GetSettingsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/settings'
        });
    }
    
    /**
     * 更新设置（fs_roots/favorite_dir 等）
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static updateSettings(data: UpdateSettingsData): CancelablePromise<UpdateSettingsResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/settings',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 验证 DB 中文件是否存在，标记缺失
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static verifyFiles(): CancelablePromise<VerifyFilesResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/settings/verify-files'
        });
    }
}

export class ThumbnailService {
    /**
     * 按实体名获取缩略图（tag/author/coser）
     * @param data The data for the request.
     * @param data.type
     * @param data.name
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static getThumbnail(data: GetThumbnailData = {}): CancelablePromise<GetThumbnailResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/thumbnail',
            query: {
                type: data.type,
                name: data.name
            }
        });
    }
}