// This file is auto-generated by @hey-api/openapi-ts

export type ArchiveEntry = {
    name: string;
    entry_path: string;
    file_type: 'image' | 'video' | 'audio' | 'unknown';
    index: number;
};

export type file_type = 'image' | 'video' | 'audio' | 'unknown';

export type ArchiveListResponse = {
    entries: Array<ArchiveEntry>;
    total: number;
};

export type AuthorListItem = {
    name: string;
    thumbnail?: (string | null);
    file_count: number;
};

export type AuthorsResponse = {
    items: Array<AuthorListItem>;
    page: number;
    page_size: number;
    total: number;
};

export type BatchParseItem = {
    filepath: string;
    result?: (ParseResponse | null);
};

export type BatchParseRequest = {
    filepaths: Array<(string)>;
};

export type BatchParseResponse = {
    items: Array<BatchParseItem>;
    parsed_count: number;
    total_count: number;
};

export type DeletePathRequest = {
    path: string;
};

export type ExtractStatus = {
    status: 'extracting' | 'completed' | 'error';
    extracted_count: number;
    total_count: number;
    cache_dir: string;
};

export type status = 'extracting' | 'completed' | 'error';

export type FileSystemItem = {
    name: string;
    path: string;
    item_type: 'folder' | 'file';
    file_type?: ('image' | 'video' | 'archive' | 'audio' | 'unknown' | null);
    filesize?: (number | null);
    mtime?: (number | null);
    thumbnail_url?: (string | null);
    recommendation_score?: (number | null);
    scan_state?: number;
    watch_state?: number;
};

export type item_type = 'folder' | 'file';

export type HistoryItem = {
    filepath: string;
    filename: string;
    file_type: 'image' | 'video' | 'archive' | 'audio' | 'unknown';
    filesize?: (number | null);
    mtime?: (number | null);
    thumbnail_url?: (string | null);
    read_at: number;
    page_current?: (number | null);
    page_total?: (number | null);
    file_exists: boolean;
};

export type file_type2 = 'image' | 'video' | 'archive' | 'audio' | 'unknown';

export type HistoryListResponse = {
    items: Array<HistoryItem>;
    page: number;
    page_size: number;
    total: number;
    total_pages: number;
};

export type HistoryRecordRequest = {
    filepath: string;
    page_current?: (number | null);
    page_total?: (number | null);
    position_sec?: (number | null);
    duration_sec?: (number | null);
};

export type HistoryRecordResponse = {
    status: "ok";
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ListResponse = {
    items: Array<FileSystemItem>;
};

export type Message = {
    message: string;
};

export type MovePathRequest = {
    source_path: string;
    dest_path: string;
};

export type ParseResponse = {
    title: string;
    authors: Array<(string)>;
    group?: (string | null);
    raw_tags: Array<(string)>;
    event?: (string | null);
    date_tag?: (string | null);
    type: string;
};

export type PathOperationResponse = {
    status: "ok";
    message: string;
    path: string;
    dest_path?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RootItem = {
    path: string;
    dirname: string;
};

export type ScanRequest = {
    path: string;
    recursive?: boolean;
};

export type ScanStartResponse = {
    status: "started";
    message: string;
    path: string;
};

export type ScanStatusItem = {
    path: string;
    status: 'running' | 'completed' | 'error';
    message?: (string | null);
    recursive?: boolean;
    scanned_folders?: number;
    scanned_files?: number;
    parsed_files?: number;
    watcher_active?: boolean;
    started_at?: (number | null);
    finished_at?: (number | null);
};

export type status2 = 'running' | 'completed' | 'error';

export type SearchRequest = {
    q?: string;
    scopes?: Array<('file' | 'author' | 'tag')>;
    mode?: 'exact' | 'hybrid';
};

export type mode = 'exact' | 'hybrid';

export type SearchResponse = {
    items: Array<FileSystemItem>;
    total: number;
};

export type StoredParseResponse = {
    filepath: string;
    title?: (string | null);
    authors?: Array<(string)>;
    group_name?: (string | null);
    raw_tags?: Array<(string)>;
    event?: (string | null);
    date_tag?: (string | null);
    media_type?: (string | null);
};

export type TagListItem = {
    name: string;
    thumbnail?: (string | null);
    file_count: number;
};

export type TagsResponse = {
    items: Array<TagListItem>;
    page: number;
    page_size: number;
    total: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ZipFolderRequest = {
    folder_path: string;
    output_path?: (string | null);
};

export type AuthorsReadAuthorsData = {
    page?: number;
    pageSize?: number;
    sortBy?: 'count' | 'name';
    sortOrder?: 'asc' | 'desc';
};

export type AuthorsReadAuthorsResponse = (AuthorsResponse);

export type FilesystemGetRootsResponse = (Array<RootItem>);

export type FilesystemGetFavoriteRootResponse = ((RootItem | null));

export type FilesystemGetDrivesResponse = (Array<RootItem>);

export type FilesystemListDirectoryData = {
    /**
     * Directory path to list
     */
    path: string;
    /**
     * Sort by field
     */
    sortBy?: 'name' | 'mtime' | 'type' | 'recommendation';
    /**
     * Sort order
     */
    sortOrder?: 'asc' | 'desc';
};

export type FilesystemListDirectoryResponse = (ListResponse);

export type FilesystemMoveFileData = {
    requestBody: MovePathRequest;
};

export type FilesystemMoveFileResponse = (PathOperationResponse);

export type FilesystemMoveFolderData = {
    requestBody: MovePathRequest;
};

export type FilesystemMoveFolderResponse = (PathOperationResponse);

export type FilesystemDeletePathData = {
    requestBody: DeletePathRequest;
};

export type FilesystemDeletePathResponse = (PathOperationResponse);

export type FilesystemZipFolderData = {
    requestBody: ZipFolderRequest;
};

export type FilesystemZipFolderResponse = (PathOperationResponse);

export type FilesystemScanFavoriteResponse = (ScanStartResponse);

export type FilesystemScanDirectoryData = {
    requestBody: ScanRequest;
};

export type FilesystemScanDirectoryResponse = (ScanStartResponse);

export type FilesystemScanAndWatchData = {
    requestBody: ScanRequest;
};

export type FilesystemScanAndWatchResponse = (ScanStartResponse);

export type FilesystemGetScanStatusData = {
    /**
     * Optional path filter
     */
    path?: (string | null);
};

export type FilesystemGetScanStatusResponse = (Array<ScanStatusItem>);

export type FilesystemGetThumbnailData = {
    /**
     * File path for thumbnail
     */
    path: string;
};

export type FilesystemGetThumbnailResponse = (unknown);

export type FilesystemListArchiveData = {
    /**
     * Archive file path
     */
    path: string;
};

export type FilesystemListArchiveResponse = (ArchiveListResponse);

export type FilesystemExtractArchiveData = {
    /**
     * Current page number for prioritized extraction
     */
    page?: number;
    /**
     * Archive file path
     */
    path: string;
};

export type FilesystemExtractArchiveResponse = (ExtractStatus);

export type FilesystemGetArchiveFileData = {
    /**
     * Entry path within archive
     */
    entry: string;
    /**
     * Archive file path
     */
    path: string;
};

export type FilesystemGetArchiveFileResponse = (unknown);

export type FilesystemGetFileData = {
    /**
     * File path
     */
    path: string;
};

export type FilesystemGetFileResponse = (unknown);

export type HistoryRecordHistoryData = {
    requestBody: HistoryRecordRequest;
};

export type HistoryRecordHistoryResponse = (HistoryRecordResponse);

export type HistoryListHistoryData = {
    page?: number;
    pageSize?: number;
    sortOrder?: 'asc' | 'desc';
};

export type HistoryListHistoryResponse = (HistoryListResponse);

export type ParseBatchParseData = {
    requestBody: BatchParseRequest;
};

export type ParseBatchParseResponse = (BatchParseResponse);

export type ParseGetParseResultData = {
    /**
     * File path to look up
     */
    filepath: string;
};

export type ParseGetParseResultResponse = (StoredParseResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SearchSearchFilesData = {
    requestBody: SearchRequest;
};

export type SearchSearchFilesResponse = (SearchResponse);

export type TagsReadTagsData = {
    page?: number;
    pageSize?: number;
    sortBy?: 'count' | 'name';
    sortOrder?: 'asc' | 'desc';
};

export type TagsReadTagsResponse = (TagsResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);