// This file is auto-generated by @hey-api/openapi-ts

export type ArchiveEntry = {
    name: string;
    entry_path: string;
    file_type: 'image' | 'video' | 'audio' | 'unknown';
    index: number;
};

export type file_type = 'image' | 'video' | 'audio' | 'unknown';

export type ArchiveListResponse = {
    entries: Array<ArchiveEntry>;
    total: number;
};

export type AuthorListItem = {
    name: string;
    thumbnail?: (string | null);
    file_count: number;
};

export type AuthorsResponse = {
    items: Array<AuthorListItem>;
    page: number;
    page_size: number;
    total: number;
};

export type BackfillRequest = {
    path: string;
    recursive?: boolean;
    fill_thumbnail?: boolean;
    fill_meta?: boolean;
};

export type BackfillResponse = {
    status: "ok";
    scanned_files: number;
    backfilled_thumbnails: number;
    backfilled_meta: number;
    message: string;
};

export type BatchParseItem = {
    filepath: string;
    result?: (ParseResponse | null);
};

export type BatchParseRequest = {
    filepaths: Array<(string)>;
};

export type BatchParseResponse = {
    items: Array<BatchParseItem>;
    parsed_count: number;
    total_count: number;
};

export type ClearCacheResponse = {
    status: "ok";
    message: string;
    deleted_files: number;
    freed_bytes: number;
    freed_size_readable: string;
};

export type CompressImagesRequest = {
    archive_path: string;
    output_path?: (string | null);
    max_width?: (number | null);
    max_height?: (number | null);
    quality?: (number | null);
    min_size?: (number | null);
};

export type CompressImagesResponse = {
    success: boolean;
    original_path: string;
    output_path: string;
    original_size: number;
    compressed_size: number;
    compression_ratio: number;
    processed_images: number;
    skipped_images: number;
    validation_passed: boolean;
    error_message?: string;
};

export type CoserListItem = {
    name: string;
    thumbnail?: (string | null);
    file_count: number;
};

export type CosersResponse = {
    items: Array<CoserListItem>;
    page: number;
    page_size: number;
    total: number;
};

export type DeletePathRequest = {
    path: string;
    permanently?: boolean;
};

export type ExtractStatus = {
    status: 'extracting' | 'completed' | 'error';
    extracted_count: number;
    total_count: number;
    cache_dir: string;
};

export type status = 'extracting' | 'completed' | 'error';

export type FileSystemItem = {
    name: string;
    path: string;
    item_type: 'folder' | 'file';
    file_type?: ('image' | 'video' | 'archive' | 'audio' | 'unknown' | null);
    filesize?: (number | null);
    mtime?: (number | null);
    thumbnail_url?: (string | null);
    recommendation_score?: (number | null);
    scan_state?: number;
    watch_state?: number;
    confidence_level?: 'certain' | 'likely_present' | 'uncertain';
    confidence_score?: number;
    image_count?: (number | null);
    video_count?: (number | null);
    audio_count?: (number | null);
    avg_image_size?: (number | null);
    last_read_at?: (number | null);
    likeScore?: (number | null);
};

export type item_type = 'folder' | 'file';

export type confidence_level = 'certain' | 'likely_present' | 'uncertain';

export type HistoryItem = {
    filepath: string;
    filename: string;
    file_type: 'image' | 'video' | 'archive' | 'audio' | 'unknown';
    filesize?: (number | null);
    mtime?: (number | null);
    thumbnail_url?: (string | null);
    read_at: number;
    page_current?: (number | null);
    page_total?: (number | null);
};

export type file_type2 = 'image' | 'video' | 'archive' | 'audio' | 'unknown';

export type HistoryListResponse = {
    items: Array<HistoryItem>;
    page: number;
    page_size: number;
    total: number;
    total_pages: number;
};

export type HistoryRecordRequest = {
    filepath: string;
    page_current?: (number | null);
    page_total?: (number | null);
    position_sec?: (number | null);
    duration_sec?: (number | null);
};

export type HistoryRecordResponse = {
    status: "ok";
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ListResponse = {
    items: Array<FileSystemItem>;
};

export type Message = {
    message: string;
};

export type MovePathRequest = {
    source_path: string;
    dest_path: string;
};

export type ParseResponse = {
    title: string;
    authors: Array<(string)>;
    cosers?: Array<(string)>;
    group?: (string | null);
    raw_tags: Array<(string)>;
    event?: (string | null);
    date_tag?: (string | null);
    type: string;
    pack_kind?: string;
};

export type PathOperationResponse = {
    status: "ok";
    message: string;
    path: string;
    dest_path?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RenameRequest = {
    path: string;
    new_name: string;
};

export type RootItem = {
    path: string;
    dirname: string;
};

export type ScanRequest = {
    path: string;
    recursive?: boolean;
};

export type ScanStartResponse = {
    status: "started";
    message: string;
    path: string;
};

export type ScanStatusItem = {
    path: string;
    status: 'running' | 'completed' | 'error';
    message?: (string | null);
    recursive?: boolean;
    scanned_folders?: number;
    scanned_files?: number;
    parsed_files?: number;
    watcher_active?: boolean;
    started_at?: (number | null);
    finished_at?: (number | null);
};

export type status2 = 'running' | 'completed' | 'error';

export type SearchRequest = {
    q?: string;
    scopes?: Array<('file' | 'author' | 'coser' | 'tag')>;
    mode?: 'exact' | 'hybrid';
    presence_filter?: 'all' | 'watched' | 'scanned_recent';
};

export type mode = 'exact' | 'hybrid';

export type presence_filter = 'all' | 'watched' | 'scanned_recent';

export type SearchResponse = {
    items: Array<FileSystemItem>;
    total: number;
};

export type SettingsResponse = {
    favorite_dir: string;
    fs_roots: string;
    already_read_dir: string;
};

export type SettingsUpdate = {
    favorite_dir?: (string | null);
    fs_roots?: (string | null);
    already_read_dir?: (string | null);
};

export type StoredParseResponse = {
    filepath: string;
    title?: (string | null);
    authors?: Array<(string)>;
    cosers?: Array<(string)>;
    group_name?: (string | null);
    raw_tags?: Array<(string)>;
    event?: (string | null);
    date_tag?: (string | null);
    media_type?: (string | null);
};

export type TagListItem = {
    name: string;
    thumbnail?: (string | null);
    file_count: number;
};

export type TagsResponse = {
    items: Array<TagListItem>;
    page: number;
    page_size: number;
    total: number;
};

export type UnzipRequest = {
    archive_path: string;
    output_dir?: (string | null);
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ZipFolderRequest = {
    folder_path: string;
    output_path?: (string | null);
};

export type AuthorsReadAuthorsData = {
    page?: number;
    pageSize?: number;
    sortBy?: 'count' | 'name';
    sortOrder?: 'asc' | 'desc';
};

export type AuthorsReadAuthorsResponse = (AuthorsResponse);

export type CosersReadCosersData = {
    page?: number;
    pageSize?: number;
    sortBy?: 'count' | 'name';
    sortOrder?: 'asc' | 'desc';
};

export type CosersReadCosersResponse = (CosersResponse);

export type FilesystemGetRootsResponse = (Array<RootItem>);

export type FilesystemGetFavoriteRootResponse = ((RootItem | null));

export type FilesystemGetAlreadyReadRootResponse = ((RootItem | null));

export type FilesystemGetDrivesResponse = (Array<RootItem>);

export type FilesystemListDirectoryData = {
    /**
     * 筛选包含音频的压缩包
     */
    hasAudio?: (boolean | null);
    /**
     * 筛选包含视频的压缩包
     */
    hasVideo?: (boolean | null);
    /**
     * Directory path to list
     */
    path: string;
    /**
     * Sort by field
     */
    sortBy?: 'name' | 'mtime' | 'type' | 'recommendation' | 'image_count';
    /**
     * Sort order
     */
    sortOrder?: 'asc' | 'desc';
};

export type FilesystemListDirectoryResponse = (ListResponse);

export type FilesystemMoveFileData = {
    requestBody: MovePathRequest;
};

export type FilesystemMoveFileResponse = (PathOperationResponse);

export type FilesystemMoveFolderData = {
    requestBody: MovePathRequest;
};

export type FilesystemMoveFolderResponse = (PathOperationResponse);

export type FilesystemDeletePathData = {
    requestBody: DeletePathRequest;
};

export type FilesystemDeletePathResponse = (PathOperationResponse);

export type FilesystemZipFolderData = {
    requestBody: ZipFolderRequest;
};

export type FilesystemZipFolderResponse = (PathOperationResponse);

export type FilesystemRenamePathData = {
    requestBody: RenameRequest;
};

export type FilesystemRenamePathResponse = (PathOperationResponse);

export type FilesystemDownloadFileData = {
    /**
     * File path to download
     */
    path: string;
};

export type FilesystemDownloadFileResponse = (unknown);

export type FilesystemUnzipArchiveData = {
    requestBody: UnzipRequest;
};

export type FilesystemUnzipArchiveResponse = (PathOperationResponse);

export type FilesystemScanFavoriteResponse = (ScanStartResponse);

export type FilesystemScanDirectoryData = {
    requestBody: ScanRequest;
};

export type FilesystemScanDirectoryResponse = (ScanStartResponse);

export type FilesystemBackfillDirectoryData = {
    requestBody: BackfillRequest;
};

export type FilesystemBackfillDirectoryResponse = (BackfillResponse);

export type FilesystemScanAndWatchData = {
    requestBody: ScanRequest;
};

export type FilesystemScanAndWatchResponse = (ScanStartResponse);

export type FilesystemGetScanStatusData = {
    /**
     * Optional path filter
     */
    path?: (string | null);
};

export type FilesystemGetScanStatusResponse = (Array<ScanStatusItem>);

export type FilesystemGetThumbnailData = {
    /**
     * File path for thumbnail
     */
    path: string;
};

export type FilesystemGetThumbnailResponse = (unknown);

export type FilesystemListArchiveData = {
    /**
     * Archive file path
     */
    path: string;
};

export type FilesystemListArchiveResponse = (ArchiveListResponse);

export type FilesystemClearExtractCacheEndpointResponse = (ClearCacheResponse);

export type FilesystemExtractArchiveData = {
    /**
     * 当前页码（基于过滤后的媒体文件列表）
     */
    page?: number;
    /**
     * 压缩包文件路径
     */
    path: string;
};

export type FilesystemExtractArchiveResponse = (ExtractStatus);

export type FilesystemGetArchiveFileData = {
    /**
     * Entry path within archive
     */
    entry: string;
    /**
     * Archive file path
     */
    path: string;
};

export type FilesystemGetArchiveFileResponse = (unknown);

export type FilesystemGetFileData = {
    /**
     * File path
     */
    path: string;
};

export type FilesystemGetFileResponse = (unknown);

export type FilesystemCompressArchiveImagesEndpointData = {
    requestBody: CompressImagesRequest;
};

export type FilesystemCompressArchiveImagesEndpointResponse = (CompressImagesResponse);

export type HistoryRecordHistoryData = {
    requestBody: HistoryRecordRequest;
};

export type HistoryRecordHistoryResponse = (HistoryRecordResponse);

export type HistoryListHistoryData = {
    page?: number;
    pageSize?: number;
    sortOrder?: 'asc' | 'desc';
};

export type HistoryListHistoryResponse = (HistoryListResponse);

export type ParseBatchParseData = {
    requestBody: BatchParseRequest;
};

export type ParseBatchParseResponse = (BatchParseResponse);

export type ParseGetParseResultData = {
    /**
     * File path to look up
     */
    filepath: string;
};

export type ParseGetParseResultResponse = (StoredParseResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SearchSearchFilesData = {
    requestBody: SearchRequest;
};

export type SearchSearchFilesResponse = (SearchResponse);

export type SettingsGetSettingsResponse = (SettingsResponse);

export type SettingsUpdateSettingsData = {
    requestBody: SettingsUpdate;
};

export type SettingsUpdateSettingsResponse = (SettingsResponse);

export type TagsReadTagsData = {
    page?: number;
    pageSize?: number;
    sortBy?: 'count' | 'name';
    sortOrder?: 'asc' | 'desc';
};

export type TagsReadTagsResponse = (TagsResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);