// This file is auto-generated by @hey-api/openapi-ts

export type ArchiveEntry = {
    name: string;
    entry_path: string;
    file_type: 'image' | 'video' | 'audio' | 'unknown';
    index: number;
};

export type file_type = 'image' | 'video' | 'audio' | 'unknown';

export type ArchiveListResponse = {
    entries: Array<ArchiveEntry>;
    total: number;
};

export type ExtractStatus = {
    status: 'extracting' | 'completed' | 'error';
    extracted_count: number;
    total_count: number;
    cache_dir: string;
};

export type status = 'extracting' | 'completed' | 'error';

export type FileSystemItem = {
    name: string;
    path: string;
    item_type: 'folder' | 'file';
    file_type?: ('image' | 'video' | 'archive' | 'audio' | 'unknown' | null);
    filesize?: (number | null);
    mtime?: (number | null);
    thumbnail_url?: (string | null);
    scan_state?: number;
    watch_state?: number;
};

export type item_type = 'folder' | 'file';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type ListResponse = {
    items: Array<FileSystemItem>;
};

export type Message = {
    message: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RootItem = {
    path: string;
    dirname: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type FilesystemGetRootsResponse = (Array<RootItem>);

export type FilesystemListDirectoryData = {
    /**
     * Directory path to list
     */
    path: string;
};

export type FilesystemListDirectoryResponse = (ListResponse);

export type FilesystemGetThumbnailData = {
    /**
     * File path for thumbnail
     */
    path: string;
};

export type FilesystemGetThumbnailResponse = (unknown);

export type FilesystemListArchiveData = {
    /**
     * Archive file path
     */
    path: string;
};

export type FilesystemListArchiveResponse = (ArchiveListResponse);

export type FilesystemExtractArchiveData = {
    /**
     * Current page number for prioritized extraction
     */
    page?: number;
    /**
     * Archive file path
     */
    path: string;
};

export type FilesystemExtractArchiveResponse = (ExtractStatus);

export type FilesystemGetArchiveFileData = {
    /**
     * Entry path within archive
     */
    entry: string;
    /**
     * Archive file path
     */
    path: string;
};

export type FilesystemGetArchiveFileResponse = (unknown);

export type FilesystemGetFileData = {
    /**
     * File path
     */
    path: string;
};

export type FilesystemGetFileResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);