/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutVideoRouteImport } from './routes/_layout/video'
import { Route as LayoutTagsRouteImport } from './routes/_layout/tags'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutHistoryRouteImport } from './routes/_layout/history'
import { Route as LayoutExplorerRouteImport } from './routes/_layout/explorer'
import { Route as LayoutCosersRouteImport } from './routes/_layout/cosers'
import { Route as LayoutAuthorsRouteImport } from './routes/_layout/authors'
import { Route as LayoutReadIndexRouteImport } from './routes/_layout/read/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVideoRoute = LayoutVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTagsRoute = LayoutTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExplorerRoute = LayoutExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCosersRoute = LayoutCosersRouteImport.update({
  id: '/cosers',
  path: '/cosers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthorsRoute = LayoutAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReadIndexRoute = LayoutReadIndexRouteImport.update({
  id: '/read/',
  path: '/read/',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/authors': typeof LayoutAuthorsRoute
  '/cosers': typeof LayoutCosersRoute
  '/explorer': typeof LayoutExplorerRoute
  '/history': typeof LayoutHistoryRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/tags': typeof LayoutTagsRoute
  '/video': typeof LayoutVideoRoute
  '/read/': typeof LayoutReadIndexRoute
}
export interface FileRoutesByTo {
  '/authors': typeof LayoutAuthorsRoute
  '/cosers': typeof LayoutCosersRoute
  '/explorer': typeof LayoutExplorerRoute
  '/history': typeof LayoutHistoryRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/tags': typeof LayoutTagsRoute
  '/video': typeof LayoutVideoRoute
  '/': typeof LayoutIndexRoute
  '/read': typeof LayoutReadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/authors': typeof LayoutAuthorsRoute
  '/_layout/cosers': typeof LayoutCosersRoute
  '/_layout/explorer': typeof LayoutExplorerRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tags': typeof LayoutTagsRoute
  '/_layout/video': typeof LayoutVideoRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/read/': typeof LayoutReadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authors'
    | '/cosers'
    | '/explorer'
    | '/history'
    | '/search'
    | '/settings'
    | '/tags'
    | '/video'
    | '/read/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/authors'
    | '/cosers'
    | '/explorer'
    | '/history'
    | '/search'
    | '/settings'
    | '/tags'
    | '/video'
    | '/'
    | '/read'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/authors'
    | '/_layout/cosers'
    | '/_layout/explorer'
    | '/_layout/history'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/tags'
    | '/_layout/video'
    | '/_layout/'
    | '/_layout/read/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/video': {
      id: '/_layout/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof LayoutVideoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tags': {
      id: '/_layout/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof LayoutTagsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/explorer': {
      id: '/_layout/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof LayoutExplorerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cosers': {
      id: '/_layout/cosers'
      path: '/cosers'
      fullPath: '/cosers'
      preLoaderRoute: typeof LayoutCosersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/authors': {
      id: '/_layout/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof LayoutAuthorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/read/': {
      id: '/_layout/read/'
      path: '/read'
      fullPath: '/read/'
      preLoaderRoute: typeof LayoutReadIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAuthorsRoute: typeof LayoutAuthorsRoute
  LayoutCosersRoute: typeof LayoutCosersRoute
  LayoutExplorerRoute: typeof LayoutExplorerRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTagsRoute: typeof LayoutTagsRoute
  LayoutVideoRoute: typeof LayoutVideoRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutReadIndexRoute: typeof LayoutReadIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthorsRoute: LayoutAuthorsRoute,
  LayoutCosersRoute: LayoutCosersRoute,
  LayoutExplorerRoute: LayoutExplorerRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTagsRoute: LayoutTagsRoute,
  LayoutVideoRoute: LayoutVideoRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutReadIndexRoute: LayoutReadIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
