name: pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  # Forks and Dependabot don't have access to secrets
  HAS_SECRETS: ${{ secrets.PRE_COMMIT != '' }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout PR for own repo
        if: env.HAS_SECRETS == 'true'
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.PRE_COMMIT }}
      - uses: actions/checkout@v4
        name: Checkout PR for fork
        if: env.HAS_SECRETS == 'false'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install
      - name: Run biome lint
        working-directory: frontend
        run: npx @biomejs/biome check --no-errors-on-unmatched --files-ignore-unknown=true ./

  # https://github.com/marketplace/actions/alls-green#why
  pre-commit-alls-green:
    if: always()
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
